### ISSUE TITLE
Porting command: giftcard:create

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#132]
Create a gift card with a specified amount

**Comment by robbieaverill** [comment]
Hi @cmuench - I can work on this, starting by cherry picking Steve's commit 74305702947f935e1266b8e164c32115c1b02ccf from the n98-magerun repository and making the required changes, however suggest that the other giftcard info and remove commands should become part of the same project since the framework for them would come over with that cherry pick too.

**Comment by ktomk** [comment]
Hi @robbieaverill, yes please do so as you see fit, sounds good.

**Comment by robbieaverill** [comment]
Hi @ktomk 

Porting done in b91767f for Create, Info and Remove (only minor adjustments required from Steve's original commit.

I have only done smoke testing at this point, but feel free to take a look at it.

Cheers,
Robbie

**Comment by ktomk** [comment]
Hi @robbieaverill, regarding your squash question: Yes, squashing will change the author details. You can preserve the author as well explicitly, however, you can credit Steve as well within the commit message ("code is based on a work by Steve ...") and I'll add him to the changes file (as you both then wrote the code) so credit is visible prominently.

As you change the file I think it's fine to change the author of the commit. However if you leave one original commit intact Steve will become part of the contributors list on Github :)

@steverobbins: Do you have any author preservation preferences?

**Comment by steverobbins** [comment]
@ktomk No preference.

**Comment by cmuench** [comment]
done.
