### ISSUE TITLE
`db:import` from stdin

### ISSUE THREAD

**Issue by maxbucknell** [netz98/n98-magerun2#154]
I want to load a database and pass it to an import without going through a file. For example

```
n98-magerun2 db:dump -c gzip --strip="@development" --stdout | \
n98-magerun2 db:import -c gzip --drop /dev/stdin
```

This worked, but the command didn't terminate properly after the command ended. I was unable to type at my terminal, and I had to exit and re-enter, at which point everything was fine.

Given you don't have an option in `db:import` for reading `stdin`, I'm guessing this is not a supported use case?

**Comment by tkn98** [comment]
Good question. `db:import` is merely a wrapper to `exec` the `mysql` program. It should be an easy test if this works when the filename parameter is made optional (try with a quick hack). Otherwise in your case it seems that end-of-file is not detected via `/dev/stdin`  which makes sense as the handle is still open even if no more data is "passed via pipe".

So far I don't understand fully why this happens what you describe.

**Comment by ktomk** [comment]
@maxbucknell: The `db:import` needs to be changed from `exec`  to `passthru`, that could work. `/dev/stdin` as `$fileName` could trigger this. Ref: https://github.com/netz98/n98-magerun2/blob/develop/src/N98/Magento/Command/Database/ImportCommand.php#L194

 And `-c gzip`  doesn't make sense with the pipe (I think).

**Comment by maxbucknell** [comment]
It's worth mentioning that the import worked perfectly. My database was imported as I expected, and it's not fair to say I couldn't type.

@ktomk The example is a silly example. What I was actually doing was dumping a file on a server and curling it and piping it in. In this case, gzip saves some bites. I love that gzip is streamable.

**Comment by tkn98** [comment]
Yes, piping is a good option.

**Comment by iaugusto-ironplane** [comment]
Related: https://github.com/netz98/n98-magerun/issues/934
