### ISSUE TITLE
Sample data fails because of authentication error

### ISSUE THREAD

**Issue by diazwatson** [netz98/n98-magerun2#176]
Every time try to install the sample data I face this issue:

> `[Composer\Downloader\TransportException]
> The 'https://repo.magento.com/packages.json' URL required authentication.
> You must be using the interactive console to authenticate
> `

I usually solved it by running `composer update` adding my credentials and then running magento `sampledata:deploy`

Until now that I stopped to think about it, realized that the issue arises because the installation is looking for credentials into the path where I am installing Magento rather than the path where my credentials  actually are `($HOME/.composer/auth.json)`, so I decided to copy my` auth.json `to the path where I am installing Magento at the moment when the question `Install sample data [y]` is prompted. As a result the issue is gone.

Question
In order to fix this, is there a way to make this credentials globally accessible?
or should I find the way to add the task of copy `auth.json` file to the current path into `n98-magerun` install tasks?

**Comment by ktomk** [comment]
> In order to fix this, is there a way to make this credentials globally accessible?

Per-project authentication in composer is done by placing an `auth.json` file next to the `composer.json` file. This is my recommendation for proper credential sharing in Magento 2 (and other composer based projects if the credentials are on a pre-project basis).

Doing this globally is *not* possible with Magento 2 (in difference to every other project) because Magento 2 changes the composer home directory occasionally that is the path you name (`$HOME/.composer/auth.json`). The directory then is inside the var folder like `/path/to/magento2-project/var/composer_home/auth.json`. An explanation why this is done [was given by @vancoz 11 days ago](https://github.com/magento/magento2/issues/2523#issuecomment-179415199)  

> Hi @ktomk, thank you for your attention to this issue, let me explain why Magento has var/composer_home directory, there is few reasons:
1. Magento actually has more than 1 user, it has at least 2 users: web server and CLI user, and we would like to use the same credentials for both of them. And this is a reason why we would like to have dedicated composer home directory and sharing composer authentication and cache between users.
2. Your current CLI user probably has different authentication setting even for the same domain (repo.magento.com) or maybe you just logged in as different user who is not authenticated yet.

 I [do not share these reasons](https://github.com/magento/magento2/issues/3108#issuecomment-179706181) especially for `auth.json` as `composer.json` is touched already, a reply to that is still pending.

But nevertheless, from the current perspective, I do recommend to place the `auth.json` file into the project directory. Done that it's also visible which credentials are in use (if any).

**Comment by diazwatson** [comment]
I see, thanks for the explanation Tom

**Comment by tkn98** [comment]
Just let me know if it's helpful for you to progress and what is working for you. Also IIRC it's possible to pre-fill the autho store via composer, we use it for the automated integration of N98-Magerun. Just ask in case you have any further questions.

**Comment by diazwatson** [comment]
Thanks @tkn98 
So far what it works for me is placing the `auth.json` file into the project directory.
I will test the technique of pre-fill the auth-store the next time I have to install M2

**Comment by ktomk** [comment]
@diazwatson: I'll close for now as I assume it works for you. If not, you can still leave comments here. Just saying.
