### ISSUE TITLE
No input on command admin:user:create

### ISSUE THREAD

**Issue by mash1t** [netz98/n98-magerun2#187]
When executing the command admin:user:create as root user, magerun doesn't allow the user to input data and completely jumps over all input options marking them red.

https://cloud.githubusercontent.com/assets/9307310/14459323/8c4b39a4-00b7-11e6-9c58-7baff03b4b94.png

**Comment by ktomk** [comment]
looks like non-interactive mode

**Comment by tkn98** [comment]
@mash1t: *admin:user:create* is provided by Magento 2 (a core command), please report this issue upstream.

You'll also find the develop version updated, -vvv will now output the concrete command-names so that you can grep whether a command is a *core command* (form Magento 2) or just a "standard" *command*.
