### ISSUE TITLE
Regression - db:dump command with @stripped only dumps structure and no data

### ISSUE THREAD

**Issue by hostep** [netz98/n98-magerun2#199]
Hi

We upgrade n98/magerun2 from 1.1.6 to 1.1.12 and noticed that the database dumps are a lot smaller then they used to be.

It looks like this is caused by the `@stripped` group, we strip out. If we omit the `strip` parameter, the dumps are correct.
If we use the `@stripped` group, we only get the structure of the tables which get stripped, but no actual data and structure of all the other tables.

The strange thing is, if I execute the db:dump command with the `--only-command` there is no difference in the `mysqdump` command output between version 1.1.6 and 1.1.12 (well except for `--pass` => `--password`).
I'm guessing the second `mysqldump` command isn't being executed.

We have this issue on 2 completely different environments, so I think anybody else should have the same problems? (aren't there any tests which should catch this btw?)

My guess is that this commit (https://github.com/netz98/n98-magerun2/commit/ba9d0ccc572881478357adfffd0e7395a3cb8bdf) might be responsible, as it changed a lot of code in the database dump command. But not sure about this, I haven't taken the time to invest this issue much further.

Thanks!

**Comment by ktomk** [comment]
@hostep: Thanks for the report, sounds like something was eaten by the update. Can you provide an example command for illustration?

**Comment by ktomk** [comment]
@hostep: Not necessary any longer, it's rather straight forward. I tested with `bin/n98-magerun2 db:dump --strip="@stripped" dump.sql` and could immediately reproduce. I'lll release a new version soon.

**Comment by hostep** [comment]
Awesome, thanks!

**Comment by ktomk** [comment]
@hostep: 1.1.13 is out that addresses this issue. To answer your question about the test: We don't test the actual execs the rest was covered. So thanks a lot for the quick report. It should be possible to add an integration test that actually compares with the file dumped and I perhaps would already have written it but right now the test-suite and build is shaky because the Magento 2 repository is down since days and the Travis build and my local testsuite heavily depends on it. Long story short: We should add a test for this scenario. With a blank install it should not be a problem.

**Comment by hostep** [comment]
Great, I can confirm everything is fine and dandy again with version 1.1.13.
Thanks once again for the quick feedback and solution!

**Comment by ktomk** [comment]
A test now covers this scenario.

**Comment by hostep** [comment]
Awesome, great job!

**Comment by ktomk** [comment]
@hostep: Also backported to Magerun 1 ;) And thank you again for your kind feedback.
