### ISSUE TITLE
Cant run on PHP 5.4.45

### ISSUE THREAD

**Issue by mpingu** [netz98/n98-magerun2#204]
I am getting an error on Running magerun-2 on a Debian 7 Server with PHP 5.4.45-1~dotdeb+7.1 

The error i am Reciving is the following:

n98-magerun2.phar list
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in phar:///usr/local/bin/n98-magerun2.phar/src/N98/Magento/Command/Customer/AbstractCustomerCommand.php on line 54

**Comment by tkn98** [comment]
@mpingu: PHP 5.4 is not supported for Magerun 2. This is not only because it is end-of-life but also because there is not support for PHP 5.4 in Magento 2  (and sooner or later no support for PHP 5.5 for Magento 2.1) .

Please ensure you've got the required PHP version if you want to run the `n98-magerun2.phar`  command.

**Comment by mpingu** [comment]
Then you should fix. 
https://github.com/netz98/n98-magerun2#compatibility
"The tools will automatically be tested for multiple PHP versions (5.4, 5.5). "

So offical you support 5.4

**Comment by tkn98** [comment]
You're right, that is outdated information. Fixed in the development version. It will require the release of the next stable version to show the changes on the Github homepage as it defaults to master. Thanks for the report and your patience @mpingu.
