### ISSUE TITLE
db:dump is ignoring the --add-time flag

### ISSUE THREAD

**Issue by tig-michielgerritsen** [netz98/n98-magerun2#281]
When i execute this command there is a filename generated without time, eg ``backup.tar.gz``. 

```bash
n98-magerun2 db:dump --add-time
```
I tried with different options, but the timestamp is never added.

**Comment by lewisvoncken** [comment]
@tig-michielgerritsen and @cmuench 

I was experiencing the same issue but I just took a look at the code and the descriptions is just incorrect because you have to pass a value as followed:\

`Invalid --add-time value %s, possible values are none (for) "suffix", "prefix" or "no"`

So the functionality works but isn't explained properly

**Comment by cmuench** [comment]
@lewisvoncken Thank you for the investigation.

**Comment by cmuench** [comment]
A better description will be available in develop version the next minutes.
