### ISSUE TITLE
Magento Install Issue with Composer auth.json Creation

### ISSUE THREAD

**Issue by perler** [netz98/n98-magerun2#300]
I am having trouble installing magento from n98:

~~~

> Please enter your public key: *************
> Please enter your private key: 
> sh: 1: : Permission denied
> 
>                                                      
>   [RuntimeException]                                 
>   Error while downloading magento, aborting install  
>                                                      
> 
>                                                                                                                                                   
>   [Symfony\Component\Process\Exception\ProcessFailedException]                                                                                    
>   The command "'' 'global' 'config' 'http-basic.repo.magento.com' ******************" failed.  
>   Exit Code: 127(Command not found)                                                                                                               
>   Working directory: /home/domain/domains/sub.domain.com/public_html                                                                              
>   Output:                                                                                                                                         
>   ================                                                                                                                                
>   Error Output:                                                                                                                                   
>   ================                                                                                                                                
>   sh: 1: : Permission denied     

~~~

I am not quite sure if this is a simple authentication problem on the magento server side or a permission problem on the local server.

**Comment by cmuench** [comment]
@perler Can you manually run this code?
```
composer.phar global config http-basic.repo.magento.com <public_key> <private_key>
```

**Comment by ignat980** [comment]
I have the same exact problem! That is the same output of `n98-magerun2 install` I thought it was a local file system permissions thing, but seems like something else. It appears after I get asked for my public/private keys.

Note: I put in my actual keys from Magento Marketplace
```
ignat@ubuntu:/var/www$ php composer.phar global config http-basic.repo.magento.com <public_key> <private_key>
Changed current directory to /home/ignat/.composer

                                                                                
  [ErrorException]                                                              
  file_put_contents(./composer.json): failed to open stream: Permission denied  
                                                                                

config [-g|--global] [-e|--editor] [-a|--auth] [--unset] [-l|--list] [-f|--file FILE] [--absolute] [--] [<setting-key>] [<setting-value>]...

ignat@ubuntu:/var/www$ 
```

My setup:
Ubuntu       16.04
apache        2.4.18
mysql          5.7.19
php             5.6.31
Magento2   2.1.7 (note, I would like to have 2.1.8, released August 9th)

**Comment by ktomk** [comment]
Normally the best answer I can give here is `auth.json`, see as well https://magento.stackexchange.com/q/90983/4115

**Comment by jschreck** [comment]
I've had the same problem. I followed @ktomk suggestion and made sure I had a valid auth.json file. 

In the end it turns out that it must be related to the location of composer.phar. 

magerun would give me the following output:

`which: no composer.phar in (/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin)
which: no composer in (/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin)
Could not find composer. Try to download it.
 Downloading: 100%/usr/bin/env php /var/www/sites/lawnpro.com/_composer_installer.php --force
Successfully installed composer to Magento root
Found executable /var/www/sites/lawnpro.com/composer.phar
which: no composer.phar in (/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin)
which: no composer in (/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin)
`

So I decided to install composer globally into /usr/local/bin and after that everything worked without a hitch. 

Hope this helps.

**Comment by ignat980** [comment]
I found out the problem. I installed composer with sudo, but ran composer without sudo. Running composer with sudo does not fix this, because composer doesn't use sudo permissions or something like that when accessing files.

Basically to fix this I needed to run the command `sudo chown www-data:www-data /home/ignat/.composer` (aka set the .composer file owner to the magento file system owner)

**Comment by perler** [comment]
re auth.json

I put a well formed auth.json in the magento root and in ~/.composer but I still get asked for the public/private key.

`{
    "http-basic": {
        "repo.magento.com": {
            "username": "email@email.com",
            "password": "***api key***"
        }
    }
}`

also, is the public key part the email address or the screen name?
![t2](https://user-images.githubusercontent.com/623092/29579369-f367e0fe-8772-11e7-977d-659a5c205f7e.jpg)

**Comment by ktomk** [comment]
It is in this format:

~~~
"http-basic": {
    "repo.magento.com": {
        "username":"<your public key>",
        "password":"<your private key>"
    }
}
~~~
So username is not the email IIRC. Pleae check with the API Keys, they are managed in the Magento account, this is not the Magento account itself.

**Comment by ktomk** [comment]
And for the initial problem this might show a flaw in Magerun. Can you run with the verbose switch (`-vvv`) and see if it shows something more fishy? It looks like the actual command (the empty string should be "`composer`") IIRC.

**Comment by JackDaniells121** [comment]
On Magento install guide there is composer command that need to paste Your public and private key as Username and Password. I write about solution of this missunderstanding for credentials on stack exchange=>https://magento.stackexchange.com/a/323146/91884
