### ISSUE TITLE
Bash autocompletion broken + warning

### ISSUE THREAD

**Issue by dvershinin** [netz98/n98-magerun2#331]
Just _updated_ autocompletion from [here](https://raw.githubusercontent.com/netz98/n98-magerun2/develop/res/autocompletion/bash/n98-magerun2.phar.bash) and got warning emitted upon every login to server or switching users via `su`:

    -bash: compdef: command not found

Googling for the error says that ```compdef``` is not even available in bash. I am **not** using zsh at all. I am using bash.  So I wonder what this line is doing in autocompletion file at all:

    compdef _n98-magerun2 n98-magerun2.phar n98-magerun2 magerun2

Server Bash version: ```GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)```

**Comment by ktomk** [comment]
This looks like an error in the autocompletion generation script we use, indeed. Thanks for the report and the clarification.

Int was `complete` (not `compdef`) earlier (ref: https://github.com/netz98/n98-magerun2/blame/e1da0b810f1f3324ecafa7278a3d364573655d0e/res/autocompletion/bash/n98-magerun2.phar.bash#L403) - which was correct.

**Comment by ktomk** [comment]
Last time that auto-completion file was generated there was a little mistake not making the bash target explicit. I just updated the development branch (and made the generation script more stable), so that the Bash auto-completion (and not Zsh) is generated even when invoked on a Zsh shell.

Please use the latest revision from the development tree for that file, you should not see that error any longer:

https://raw.githubusercontent.com/netz98/n98-magerun2/4038599a874ffd5f4ff028a632f49f794c5e68ff/res/autocompletion/bash/n98-magerun2.phar.bash
