### ISSUE TITLE
Feature request: opposite of db:dump exclude/strip: include only

### ISSUE THREAD

**Issue by lingwooc** [netz98/n98-magerun2#371]
It would be really useful to have the option to do the opposite of a strip/exclude. So I might call:

```
n98-magerun2.phar  db:dump --include-only="@trade"
```

And get just those tables. I had call to use this today to update my sales tables from the "production" server to the "soon to be production" server.

As it happened I just used the --only-command option and adjusted the mysqldump command manually.

**Comment by zainengineer** [comment]
n98-magerun for magento 1 has a similar feature
https://github.com/netz98/n98-magerun/pull/848

It will be great of we have it for magento 2 as well.
Specially useful for core_config_data dump. 
bin/magento supports app:config:dump but exporting a single table will be more useful.

**Comment by bdnugget** [comment]
This can be closed since it is now a feature right?

I do however have another feature request, namely a --exclude option for db:import to be able to do --exclude=core_config_data if you forgot to exclude it from your dump. Should I open a new issue for this request or is there already an existing solution that I'm not aware of?

**Comment by cmuench** [comment]
@bdnugget good finding. This was already backported or is it a forward :smile: 
I close this issue here.
