### ISSUE TITLE
Fatal Error : undefined method N98\Magento\Application::isSingleCommand()

### ISSUE THREAD

**Issue by AreDubya** [netz98/n98-magerun2#432]
Hello, 

I have run into an error when running any command with the `-h` or `--help` flag in place. 

_**Error :**_ 
```
PHP Fatal error:  Uncaught Error: Call to undefined method N98\Magento\Application::isSingleCommand() in /var/www/html/vendor/symfony/console/Command/Command.php:528
Stack trace:
#0 phar:///usr/local/bin/magerun2/vendor/symfony/console/Descriptor/TextDescriptor.php(157): Symfony\Component\Console\Command\Command->getProcessedHelp()
#1 phar:///usr/local/bin/magerun2/vendor/symfony/console/Descriptor/Descriptor.php(52): Symfony\Component\Console\Descriptor\TextDescriptor->describeCommand(Object(Magento\Deploy\Console\Command\ShowModeCommand), Array)
#2 phar:///usr/local/bin/magerun2/vendor/symfony/console/Helper/DescriptorHelper.php(69): Symfony\Component\Console\Descriptor\Descriptor->describe(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Magento\Deploy\Console\Command\ShowModeCommand), Array)
#3 /var/www/html/vendor/symfony/console/Command/HelpCommand.php(76): Symfony\Component\Console\Helper\DescriptorHelper->describe(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Magento\Deploy\Console\Comman in /var/www/html/vendor/symfony/console/Command/Command.php on line 528
```

_**Environment :**_ 

- n98-magerun2 version 3.0.3

- Magento 2.3.0

- Composer version 1.8.3

- PHP 7.1.26-1

- Apache/2.4.29 (Ubuntu)

- MySQL : 5.7.25-0ubuntu0.18.04

- Ubuntu 18.04.1

_**Behavior :**_ 

The help section completes (`-v|vv|vvv, --verbose` starts the last line) but the error I pasted above happens immediately after.  This happens with deploy mode set to either `developer` or `production`.

I couldn't find a report of the same error, hopefully this isn't well-trod ground. Thanks for the amazing tool!

**Comment by cmuench** [comment]
@AreDubya Thanks for reporting. I could confirm that this error occurs in a Magento 2.3.0 instance.

**Comment by cmuench** [comment]
@AreDubya I will try to release a new version today. A fix is already merged in the develop version.
You can upgrade with "n98-magerun2.phar self-update --unstable".

**Comment by AreDubya** [comment]
@cmuench Thanks! Above and beyond as always, drinks are on me if we cross paths at a conference.

**Comment by romeof1980** [comment]
hi @cmuench 
we've got the same issue with n98-magerun2 4.0.3. on Magento 2.3.3 (php 7.2.25) 
updating to --unstable does not help (updates to 4.0.3)
**step to reproduce:**
n98-magerun2 admin:user:change-password myusername
fails when calling following helper 
$password = $questionHelper->ask($input, $output, $question);
on src/N98/Magento/Command/Admin/User/ChangePasswordCommand.php  line 70
calls ($questionHelper) vendor/symfony/console/Helper/QuestionHelper.php (function ask(), line 46) and then n98-magerun2.phar/vendor/symfony/console/Helper/QuestionHelper.php function doAsk (line 119) when calling:
$autocomplete = $question->getAutocompleterCallback();

getAutocompleterCallback() fails because $question (namespace Symfony\Component\Console\Question\Question that is vendor/symfony/console/Question/Question.php) has go NO getAutocompleterCallback() method.

Why is QuestionHelper.php calling an unexisting method? I don't see Question extending from other classes hence no need to look for the method in parents. Am I correct?
Ar we missing a method here? See attachments. 
Any idea?

![2-calling-nonexistent-getAutocompleterCallback](https://user-images.githubusercontent.com/11228308/76164619-9aee5080-610d-11ea-9b79-8123aa7e0f5a.png)

![1-no-getAutocompleterCallback](https://user-images.githubusercontent.com/11228308/76164617-96c23300-610d-11ea-893e-016ab49646e8.png)

![3-error-calltoundefinedmethod-getAutocompleterCallback](https://user-images.githubusercontent.com/11228308/76164623-9fb30480-610d-11ea-86a9-a993636215a5.png)

**Comment by cmuench** [comment]
@romeof1980 see #521 for more details.
Do you use a Magento with an optimized composer autoloader?

**Comment by romeof1980** [comment]
thanks @cmuench for pointing it out.
I don't see any way an optimized composer autoloader could be enable on my application (set on developer mode). I use this as a reference (https://getcomposer.org/doc/articles/autoloader-optimization.md) and I can confirm my composer.json has got no "optimize-autoloader" in it.
Furthermore, I do not see how the getAutocompleterCallback() is supposed to work (see screenshot above). 
It's an undefined method and I reckon we see a pure phperror here

**Comment by cmuench** [comment]
@romeof1980 Please see: https://github.com/netz98/n98-magerun2/issues/521#issuecomment-596765051
