### ISSUE TITLE
Add admin user role to admin:user:create

### ISSUE THREAD

**Issue by nbennett25** [netz98/n98-magerun2#489]
We're seeing an issue where running `admin:user:create [options]` creates the admin user, but fails to assign a user role, so the newly created user is unable to log in. 

Could we get `--admin-user-role=[Role Name]` added as an option?

**Comment by ktomk** [comment]
Can you please additionally share the version of Magerun and Magento you experience this on?

**Comment by nbennett25** [comment]
Actually @ktomk `admin:user:create` is part of the built in Magento CLI commands - I thought it was Magerun2 specific. We can build out a composer patch for that command to include the admin role option.

**Comment by ktomk** [comment]
@nbennett25: thanks for the update. Also feel free to share your patch here if you see it fit. Other users might stumble over the same if you think it's helpful.

**Comment by amenk** [comment]
As a workaround, one can execute this SQL after admin:user:create

(would assign "My Role" to "restricted_user")

```bash
echo 'UPDATE authorization_role SET parent_id = (SELECT role_id FROM authorization_role
    WHERE role_name = '\''My Role'\'')
    WHERE user_id = (SELECT user_id FROM admin_user WHERE username = '\''restricted_user'\'') AND tree_level = 2; | n98-magerun2 db:console --no-interaction'
```

@cmuench Would that be in scope for Magerun2 in the future? Maybe it can be added as an additional command `admin:user:change-role` instead of overloading the current Magento core command.

Feel free to reopen :-)
